### ISSUE TITLE
Clarify 1-3 science questions that we could answer in short-term (~<1 year) with information from ‘Mandatory input fields’

### ISSUE THREAD

**Issue by tomglee** [juancastilla/GroMoPo#6]

**Comment by tomglee** [comment]
good conversation about this and I updated Table with some suggestions, primarily from Kevin 
https://docs.google.com/document/d/1-JuPQkj7HTBAaVJUUNX_1CgUJlSf7wQemj8EjWZ9boY/edit?usp=sharing

**Comment by juancastilla** [comment]
@tomglee can we declare this issue as closed?
