### ISSUE TITLE
UX improvements based on meeting June 1 (Tom and Juan)

### ISSUE THREAD

**Issue by juancastilla** [juancastilla/GroMoPo#7]
See Tom's Google Slides. Goal is to visualise CA and WA models provided by Kevin

**Comment by kbefus** [comment]
Some relatively quick notes from the meeting/Tom's slides

### Home page:
- Auto-counter for model scales located near/above images

### Portal page:
- Inge's water table depth (and maybe head) as basemaps
- Page name: "Explore models"/"Find models"/etc

### Organization:
- 4 total pages: Home/Landing, Portal, Share Data, and About
- Statement about model "ownership" and opportunity for model developers to update/override database entries, even if they didn't originally submit it to the repository
-

**Comment by tomglee** [comment]
Juan, can you add Kevin officially to repository? then he can be added as assignee on issue...

**Comment by tomglee** [comment]
Juan, what is happening with this? any help/support i can provide to get these two things done for the sprint next week? Tom

**Comment by juancastilla** [comment]
> Juan, can you add Kevin officially to repository? then he can be added as assignee on issue...

Done! @kbefus should have an invite in his inbox

**Comment by juancastilla** [comment]
> Juan, what is happening with this? any help/support I can provide to get these two things done for the sprint next week? Tom

Hi @tomglee  I've been swamped with other deadlines the last couple of weeks. I'll sit down for a couple of hours now to make some progress. It's a public holiday in Australia today so I'll do what I can...

**Comment by juancastilla** [comment]
Done! Changes should be reflected on the app
